### ISSUE TITLE
🚀 Feature: Port and rethink error handling flow

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [bingo-js/bingo#81]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

If create-typescript-app catches a thrown error / rejection during repository creation, it displays it fully and offers to `git restore` the repository locally:

```plaintext
│
◇  ✅ Passed clearing any local Git tags.
│
◇  ❌ Error initializing GitHub repository.
│
Error: Failed initializing GitHub repository
    at withSpinner (file:///Users/josh/repos/create-typescript-app/lib/shared/cli/spinners.js:16:11)

...

    at async file:///Users/josh/repos/create-typescript-app/bin/index.js:4:20 {
  [cause]: RequestError [HttpError]: Validation Failed: "Missing required parameter `exclude`" - https://docs.github.com/rest/repos/rules#create-a-repository-ruleset
      at file:///Users/josh/repos/create-typescript-app/node_modules/.pnpm/@octokit+request@9.1.1/node_modules/@octokit/request/dist-bundle/index.js:106:21

...

}
│
◇  Do you want to restore the repository to how it was?
```

That error visualization is pretty clunky, but it does include _all_ information. And the option to restore the repo is... nice, I guess?

I'll want to rethink this and implement a cleaner equivalent in `create`.

### Additional Info

💖

**Comment by JoshuaKGoldberg** [comment]
On second look, I think I'm only going to port nice wrapping of errors. Offering to reset the repository sounds nice in theory but in practice I've never actually used it. And it's really just a small wrapper around `git restore .`
